import { Stack } from '@chakra-ui/react'
import Head from 'next/head'


export default function Home() {
  return (
    <Stack minH='100vh' bgColor='hsl(218, 28%, 13%)' >
      <Head>
        <title>Fylo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
    </Stack>
  )
}
