import { Stack } from '@chakra-ui/react'
import Head from 'next/head'
import Header from '../components/header/Header'
import Navbar from '../components/navbar/Navbar'


export default function Home() {
  return (
    <Stack minH='100vh' bgColor='hsl(218, 28%, 13%)' overflow='hidden' >
      <Head>
        <title>Fylo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack h='100vh' bg='hsl(217, 28%, 15%)'>
        <Navbar />
        <Header />
      </Stack>
      <Stack minH='100vh' w='100vw'>

      </Stack>
    </Stack>
  )
}
